name: Terraform Modules CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  validate-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version:  1.12.2 # pick the version you want

      - name: Validate modules
        run: |
            set -euo pipefail
            
            for dir in modules/*/; do
              echo "🔍 Checking module: $dir"
              cd "$dir"
            
              echo "→ terraform fmt -check"
              if ! terraform fmt -check -recursive; then
                echo "❌ Formatting issues in $dir"
                exit 1
              fi
            
              echo "→ terraform init"
              if ! terraform init -backend=false -input=false -no-color; then
                echo "❌ Init failed in $dir"
                exit 1
              fi
            
              echo "→ terraform validate"
              if ! terraform validate -no-color; then
                echo "❌ Validation failed in $dir"
                exit 1
              fi
            
              cd - > /dev/null
              echo "✅ $dir passed validation"
            done
